[package]
name = "RusticFish"
version = "0.1.0"
authors = ["Tim Vrakas <tim.vrakas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
